package order.processing.system;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

public class OrderDetailUI extends javax.swing.JFrame {

    TransferListCntl TLC;
    OrderListCntl OLC;
    private OrderDetailTableModel ODTM;
    ArrayList<Inventory> cart;
    private int orderID;
    private int desiredItem;
    
    public OrderDetailUI(TransferListCntl inputTLC, int inputOrderID, int inputDesiredItem, ArrayList<Inventory> inputCart, boolean performTransfer)
    {
        TLC = inputTLC;
        cart = inputCart;
        ODTM = new OrderDetailTableModel(cart);
        orderID = inputOrderID;
        desiredItem = inputDesiredItem;
        initComponents();
        transferButton.setVisible(performTransfer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        orderDetailTable = new javax.swing.JTable();
        closeButton = new javax.swing.JButton();
        transferButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        orderDetailTable.setModel(ODTM);
        jScrollPane1.setViewportView(orderDetailTable);

        closeButton.setText("X");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        transferButton.setText("Perform Transfer");
        transferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(transferButton)
                        .addGap(199, 199, 199))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeButton)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(transferButton)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void transferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferButtonActionPerformed
        int selectedTableRow = orderDetailTable.getSelectedRow();
        int selectedModelRow = orderDetailTable.convertRowIndexToModel(selectedTableRow);
        try {
            TLC.createTransfer(orderID, selectedModelRow, desiredItem);
        } catch (SQLException ex) {
            Logger.getLogger(OrderDetailUI.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("SQL Exception");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OrderDetailUI.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("ClassNotFound");
        }
    }//GEN-LAST:event_transferButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orderDetailTable;
    private javax.swing.JButton transferButton;
    // End of variables declaration//GEN-END:variables
}
